package com.splitease.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Persistent state for a connection invite to a phantom user.
 *
 * This entity is stored in Room (not DataStore) because:
 * 1. Connection state references phantomLocalUserId which exists in Room's users table
 * 2. FK CASCADE ensures automatic cleanup when phantom user is deleted
 * 3. Transactional safety with merge operations
 *
 * Lifecycle:
 * 1. INVITE_CREATED - Invite generated, waiting for claim
 * 2. CLAIMED - Other party claimed, ready for merge
 * 3. MERGED - Phantom → Real merge complete (then deleted via cascade)
 */
@Entity(
    tableName = "connection_states",
    foreignKeys = [
        ForeignKey(
            entity = User::class,
            parentColumns = ["id"],
            childColumns = ["phantomLocalUserId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("phantomLocalUserId", unique = true)]
)
data class ConnectionStateEntity(
    @PrimaryKey
    val phantomLocalUserId: String,

    /**
     * Unique invite token generated by backend.
     * Format: inv_<random_hex>
     */
    val inviteToken: String,

    /**
     * Current status of the connection.
     */
    val status: ConnectionStatus,

    /**
     * Cloud user ID of the person who claimed the invite.
     * Null until CLAIMED.
     */
    val claimedByCloudUserId: String? = null,

    /**
     * Display name of the person who claimed the invite.
     * Null until CLAIMED.
     */
    val claimedByName: String? = null,

    /**
     * Timestamp of last status check against backend.
     */
    val lastCheckedAt: Long = System.currentTimeMillis()
)
