package com.splitease.data.repository

import com.splitease.data.local.dao.UserDao
import com.splitease.data.local.entities.User
import kotlinx.coroutines.flow.Flow
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class UserRepositoryImpl @Inject constructor(
    private val userDao: UserDao
) : UserRepository {

    /**
     * Observes all users in the data source.
     *
     * Emits updates whenever the stored list of users changes.
     *
     * @return A Flow that emits the current list of User entities; emits a new list whenever the underlying data changes.
     */
    override fun getAllUsers(): Flow<List<User>> {
        return userDao.getAllUsers()
    }

    /**
     * Provides a stream of the user with the given id.
     *
     * @param userId The id of the user to observe.
     * @return A `Flow` that emits the matching `User`, or `null` if no user exists with that id.
     */
    override fun getUser(userId: String): Flow<User?> {
        return userDao.getUser(userId)
    }

    /**
     * Creates a new "phantom" user, persists it, and returns the repository-generated user ID.
     *
     * The created user uses a UUID generated by the repository, the provided name,
     * trimmed email and phone (blank or null values are converted to `null`), and a `null` profileUrl.
     *
     * @param name The user's display name.
     * @param email The user's email; leading and trailing whitespace are trimmed and blank or `null` values become `null`.
     * @param phone The user's phone number; leading and trailing whitespace are trimmed and blank or `null` values become `null`.
     * @return The newly generated user ID.
     */
    override suspend fun createPhantomUser(name: String, email: String?, phone: String?): String {
        // Generate UUID internally - Repository is the authority on ID generation
        val newUserId = UUID.randomUUID().toString()
        
        // Create the user entity
        // Note: profileUrl is intentionally null for phantom users
        val newUser = User(
            id = newUserId,
            name = name,
            email = email?.trim()?.ifBlank { null },
            phone = phone?.trim()?.ifBlank { null },
            profileUrl = null
        )
        
        userDao.insertUser(newUser)
        return newUserId
    }
}